name: QML Label component check
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: QML Label component check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run label component count
        run: |
          MATCHESRESULT=$(find . -iname "*.qml" | xargs grep -r -e "^\s*Label\s*[{]" | wc -l | sed "s/ //g")
          echo "MATCHES=${MATCHESRESULT}" >> $GITHUB_ENV
          echo "EXPECTED_MATCHES=1" >> $GITHUB_ENV
      - name: Check label component use count
        if: env.MATCHES != env.EXPECTED_MATCHES
        uses: actions/github-script@v7
        with:
          script: |
              core.setFailed('Using QML Labels! Make sure to use EnforcedPlainTextLabel instead!')
